crm/urls.py
from django.conf.urls import url
from crm.views import auth
from crm.views import customer,teacher

urlpatterns = [
    url(r'^login/$',auth.Login.as_view(),name='login'),
    url(r'^register/$',auth.Reg.as_view(),name='register'),
    url(r'^index/$', auth.Index.as_view(), name='index'),
    # url(r'^show_customer/',customer.Customer.as_view(),name='show_customer'),
    url(r'^add_customer/$',customer.CustomerChange.as_view(),name='add_customer'),
    url(r'^edit_customer/(\d+)$',customer.CustomerChange.as_view(),name='edit_customer'),

    url(r'^public_customer/$',customer.CustomerList.as_view(),name='public_customer'),
    url(r'^private_customer/$',customer.CustomerList.as_view(),name='private_customer'),

    # 展示所有的跟进记录
    url(r'^consult_record/$',customer.ConsultList.as_view(),name='consult_record'),
    # 展示某个客户的跟进记录
    url(r'^consult_record/(\d+)$',customer.ConsultList.as_view(),name='someone_consult'),
    url(r'^add_consult/$',customer.AddConsult.as_view(),name='add_consult'),
    url(r'^edit_consult/(\d+)$',customer.EditConsult.as_view(),name='edit_consult'),
        
    url(r'^enrollment/$',customer.Enrollment.as_view(),name='enrollment'),
    url(r'^add_enrollment/(?P<customer_id>\d+)$',customer.EnrollmentChange.as_view(),name='add_enrollment'),
    url(r'^edit_enrollment/(?P<edit_id>\d+)$',customer.EnrollmentChange.as_view(),name='edit_enrollment'),
        
    url(r'^class_list/$',teacher.ClassList.as_view(),name='class_list'),
    url(r'^add_class_list/$',teacher.ClassListChange.as_view(),name='add_class_list'),
    url(r'^edit_class_list/(?P<edit_id>\d+)$',teacher.ClassListChange.as_view(),name='edit_class_list'),

    url(r'^course_record/(?P<class_id>\d+)$',teacher.CourseRecord.as_view(),name='course_record'),
    url(r'^add_course_record/(?P<class_id>\d+)$',teacher.CourseRecordChange.as_view(),name='add_course_record'),
    url(r'^edit_course_record/(?P<edit_id>\d+)$',teacher.CourseRecordChange.as_view(),name='edit_course_record'),

    url(r'^study_record_list/(?P<course_record_id>\d+)$',teacher.StudyRecordList.as_view(),name='study_record_list'),
]

practic_crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from crm import pagenation

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crm/',include('crm.urls')),
    url(r'^rbac/',include('rbac.urls',namespace='rbac')),
    # url(r'^pagenation/',pagenation.pagenation),
]

crm/models.py
from django.db import models
from multiselectfield import MultiSelectField
from rbac.models import User

course_choices = (('Linux', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Department(models.Model):
    """
    部门表
    """
    name = models.CharField(max_length=32, verbose_name="部门名称")
    count = models.IntegerField(verbose_name="人数", default=0)


class UserProfile(User):
    """
    用户表
    """
    username = models.EmailField(max_length=255, unique=True, )
    password = models.CharField(max_length=128)
    name = models.CharField('名字', max_length=32)
    department = models.ForeignKey('Department', default=None, blank=True, null=True)
    mobile = models.CharField('手机', max_length=32, default=None, blank=True, null=True)
    memo = models.TextField('备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", )

    def __str__(self):
        return "{} - {}".format(self.qq, self.name)

    def show_class(self):
        return '  '.join([str(i) for i in self.class_list.all()])

    def show_status(self):
        color_dict = {
            'signed': '#31b731',
            'unregistered': 'red',
            'studying': 'blue',
            'paid_in_full': 'yellow',
        }
        return '<span style="color:{}">{}</span>'.format(color_dict.get(self.status),self.get_status_display())

class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name

class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区")
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{} - {} ({})".format(self.get_course_display(), self.semester, self.campuses.name)



class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """
    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
    customer = models.ForeignKey('Customer', verbose_name="客户")
    consultant = models.ForeignKey('UserProfile', verbose_name="销售")
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name="班级")
    teacher = models.ForeignKey('UserProfile', verbose_name="讲师",related_name='t_course_records')
    recorder = models.ForeignKey('UserProfile', verbose_name="记录者",related_name='r_course_records')

    class Meta:
        unique_together = ('re_class', 'day_num')

    def __str__(self):
        return "{}- day{}".format(self.re_class,self.day_num)

class StudyRecord(models.Model):
    """
    学习记录
    """

    attendance = models.CharField("考勤", choices=attendance_choices, default="checked", max_length=64)
    score = models.IntegerField("本节成绩", choices=score_choices, default=-1)
    homework_note = models.CharField(max_length=255, verbose_name='作业批语', blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)

crm/views/teacher.py
from django.shortcuts import render,HttpResponse,redirect,reverse
from django.views import View
from crm import models
from crm.forms import ClassListForm,CourseRecordForm,StudyRecordForm
from crm.pagenation import Pagenation
from django.db.models import Q
from django.conf import settings
from django.db import transaction
from django.contrib import messages

class BaseView(View):
    def search(self,filter_list):
        querry=self.request.GET.get('querry','')
        q=Q()
        for i in filter_list:
            q.children.append(Q(('{}__contains'.format(i),querry)))
        # children=[Q({}}__contains=querry),
        q.connector='OR'
        return q

class ClassList(BaseView):

    def get(self,request):
        q=self.search([])
        query_dict=request.GET.copy()
        classlist_obj = models.ClassList.objects.filter(q,)
        page = Pagenation(classlist_obj, 5, 2, query_dict)
        context = {'date':page.current_page_show_data,
        'pagenation_html':page.navgation,}
        return render(request, 'teacher\class_list.html', context)

class ClassListChange(BaseView):
    def get(self,request,edit_id=None):
        class_list_obj=models.ClassList.objects.filter(pk=edit_id).first()
        class_list_form=ClassListForm(instance=class_list_obj)
        title='添加班级' if edit_id else '编辑班级'
        return render(request,'form.html',{'form_obj':class_list_form,'title':title})

    def post(self,request,edit_id=None):
        class_list_obj=models.ClassList.objects.filter(pk=edit_id).first()
        class_list_form=ClassListForm(request.POST,instance=class_list_obj)
        if class_list_form.is_valid():
            class_list_form.save()
            need_page=request.GET.get('final')
            return redirect(need_page)
        title='添加班级' if edit_id else '编辑班级'
        return render(request, 'form.html', {'form_obj': class_list_form,'title': title})

class CourseRecord(BaseView):
    def get(self,request,class_id):
        q=self.search([])
        query_dict=request.GET.copy()
        course_record_obj = models.CourseRecord.objects.filter(q,re_class_id=class_id)
        page = Pagenation(course_record_obj, 5, 2, query_dict)
        context = {'date':page.current_page_show_data,
        'pagenation_html':page.navgation,
        'class_id':class_id}
        return render(request, 'teacher\course_record_list.html', context)
    
    def post(self,request,class_id):
        course_record_ids=request.POST.getlist('ids',[])
        for course_record_id in course_record_ids:
            course_record_obj=models.CourseRecord.objects.filter(pk=course_record_id).first()
            students = course_record_obj.re_class.customer_set.filter(status='studying')
            study_record_list = []
            for student in students:
                if not models.StudyRecord.objects.filter(student=student, course_record_id=course_record_id).exists():
                    study_record_list.append(models.StudyRecord(student=student, course_record_id=course_record_id))

            models.StudyRecord.objects.bulk_create(study_record_list)
        return self.get(request,class_id)


    
class CourseRecordChange(BaseView):
    def get(self,request,class_id=None,edit_id=None):
        if class_id and not edit_id:
            obj=models.CourseRecord(re_class_id=class_id,recorder_id=request.session['pk'])
            title='添加课程记录'
        else:
            obj=models.CourseRecord.objects.filter(pk=edit_id).first()
            title='编辑课程记录'
        courserecord_form=CourseRecordForm(instance=obj)
        return render(request,'form.html',{'form_obj': courserecord_form,'title': title})

    def post(self,request,class_id=None,edit_id=None):
        if class_id and not edit_id:
            obj=models.CourseRecord(re_class_id=class_id,recorder_id=request.session['pk'])
            title='添加课程记录'
        else:
            obj=models.CourseRecord.objects.filter(pk=edit_id).first()
            title='编辑课程记录'
        courserecord_form=CourseRecordForm(request.POST,instance=obj)
        if courserecord_form.is_valid():
            courserecord_form.save()
            need_page=request.GET.get('final')
            return redirect(need_page)
        return render(request,'form.html',{'form_obj': courserecord_form,'title': title})
        
from django.forms import modelformset_factory
from django.contrib import messages

class StudyRecordList(BaseView):
    def get(self,request,course_record_id):
        FormSet=modelformset_factory(models.StudyRecord,form=StudyRecordForm,extra=0)
        formset_obj = FormSet(queryset=models.StudyRecord.objects.filter(course_record_id=course_record_id))
        return render(request, 'teacher\study_record_list.html',{'formset_obj':formset_obj})
    
    def post(self,request,course_record_id):
        FormSet=modelformset_factory(models.StudyRecord,form=StudyRecordForm,extra=0)
        formset_obj = FormSet(data=request.POST)
        if formset_obj.is_valid():
            messages.success(request,'保存成功！')
            formset_obj.save()
        return render(request, 'teacher\study_record_list.html',{'formset_obj':formset_obj})

crm/templates/add_customer.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">添加客户</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in customer_obj %}
                    <div class="form-group {% if field.errors %}has-error{% endif %} ">
                        <label for="{{ field.id_for_label }}"
                               class="col-sm-2 col-sm-offset-1 control-label">{{ field.label }}</label>
                        <div class="col-sm-4">
                            {{ field }}
                            <span class="help-block">{{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

crm/templates/addconsult.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in form_obj %}
                    <div class="form-group {% if field.errors %}has-error{% endif %} ">
                        <label for="{{ field.id_for_label }}"
                               class="col-sm-2 col-sm-offset-1 control-label">{{ field.label }}</label>
                        <div class="col-sm-4">
                            {{ field }}
                            <span class="help-block">{{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

crm/templates/consult.html
{% extends 'layout.html' %}

{% block content%}
    <p><a class="btn btn-primary" href="{% url 'add_consult' %}">新增</a></p> 
    <form class="form-inline pull-right" style="margin-left: 70px;">
        <input name='querry' class="form-control form-inline" type="text" placeholder="输入关键字">
        <button class="btn btn-primary">搜索</button>
    </form>
    <form class="form-inline" action="" method="post">
    {% csrf_token %}
    <!-- <div>
        <div style="">
            <span style="line-height: 35px;" class="">选择需要的操作</span>
            <select class="form-control" name="batch" id="">

            </select>
            <button class="btn btn-primary">提交</button>
        </div>       
    </div> -->
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>选择</th>
            <th>序号</th>
            <th>跟进内容</th>
            <th>状态</th>
            <th>跟进日期</th>
            <th>查看跟进</th>
            <th>咨询的客户</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        {% for consult in date %}
        <tr>
            <td><input type="checkbox" name="ids" value="{{ consult.pk }}"></td>
            <td>{{ forloop.counter }}</td>
            <td>{{ consult.note|truncatechars:'30' }}</td>
            <td>{{ consult.get_status_display }}</td>
            <td>{{ consult.date|date:'Y-m-d H:i:s' }}</td>           
            <td><a href="{% url 'someone_consult' consult.customer_id %}"><i class="fa fa-list-ul" aria-hidden="true"></i></a></td>
            <td>{{ consult.customer }}</td>
            {#<td><a href="{% url 'edit_consult' consult.pk %}"> <i class="fa fa-edit"></i></a>#}
            {% load mytags %}
            <td><a href="{% return_url request 'edit_consult' consult.pk %}"> <i class="fa fa-edit"></i> </a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<nav aria-label="Page navigation">
    <ul class="pagination">
        {{ pagenation_html|safe }}
    </ul>
</nav>
</form>
{% endblock %}

crm/templates/customer.html
{% extends 'layout.html' %}

{% block content%}
    <p><a class="btn btn-primary" href="{% url 'add_customer' %}">新增</a></p> 
    <form class="form-inline pull-right" style="margin-left: 70px;">
        <input name='querry' class="form-control form-inline" type="text" placeholder="输入关键字">
        <button class="btn btn-primary">搜索</button>
    </form>
    <form class="form-inline" action="" method="post">
    {% csrf_token %}
    <div>
        <div style="">
            <span style="line-height: 35px;" class="">选择需要的操作</span>
            <select class="form-control" name="batch" id="">
                {% if request.path_info == '/crm/public_customer/' %}
                    <option value="pub_to_pri">公共用户变为私人用户</option>
                {% else %}
                    <option value="pri_to_pub">私人用户变为公共用户</option>
                {% endif %}
            </select>
            <button class="btn btn-primary">提交</button>
        </div>
        
        
    </div>
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <td>批量</td>
            <td>序号</td>
            <td>QQ</td>
            <td>姓名</td>
            <td>性别</td>
            <td>手机号</td>
            <td>客户来源</td>
            <td>咨询课程</td>
            <td>状态</td>
            <td>添加报名</td>
            <td>跟进时间</td>
            <td>销售</td>
            <td>班级</td>
            <td>操作</td>
        </tr>
    </thead>
    <tbody>
    {% for customer in date %}
        <tr>
            <td><input type="checkbox" name="ids" value="{{ customer.pk }}"></td>
            <td>{{ forloop.counter }}</td>
            <td>{{ customer.qq }}</td>
            <td>{{ customer.name|default:'暂无' }}</td>
            <td>{{ customer.get_sex_display }}</td>
            <td>{{ customer.phone }}</td>
            <td>{{ customer.get_source_display }}</td>
            <td>{{ customer.course }}</td>
            <td>{{ customer.show_status|safe }}</td>
            {% load mytags %}
            <td><a href="{% return_url request 'add_enrollment' customer_id=customer.pk %}"><i class="fa fa-plus-square" aria-hidden="true"></i></a></td>
            <td>{{ customer.last_consult_date|date:'Y-m-d' }}</td>
            <td>{{ customer.consultant|default:'暂无' }}</td>
            <td>{{ customer.show_class }}</td>
            <td><a href="{% return_url request 'edit_customer' customer.pk %}"> <i class="fa fa-edit"></i> </a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<nav aria-label="Page navigation">
    <ul class="pagination">
        {{ pagenation_html|safe }}
    </ul>
</nav>
</form>
{% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
{% endif %}
{% endblock %}

crm/templates/enrollment.html
{% extends 'layout.html' %}

{% block content %}
    <form class="form-inline pull-right" style="margin-left: 70px;">
        {% csrf_token %}
        <input name='querry' class="form-control form-inline" type="text" placeholder="输入关键字">
        <button class="btn btn-primary">搜索</button>
    </form>
    <form action="" method="post" class="form-inline">
        {% csrf_token %}
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>选择</th>
                <th>序号</th>
                <th>报名原因</th>
                <th>期望值</th>
                <th>报名日期</th>
                <th>客户</th>
                <th>校区</th>
                <th>班级</th>
                <th>审核状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for enrollment in date %}
                <tr>
                    <td><input type="checkbox" name="ids" value="{{ enrollment.pk }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ enrollment.why_us }}</td>
                    <td>{{ enrollment.your_expectation }}</td>
                    <td>{{ enrollment.enrolled_date|date:'Y-m-d H:i:s' }}</td>
                    <td>{{ enrollment.customer }}</td>
                    <td>{{ enrollment.school }}</td>
                    <td>{{ enrollment.enrolment_class }}</td>
                    <td>{% if enrollment.contract_approved %}
                        是
                    {% else %}
                        否
                    {% endif %}</td>
                    {% load mytags %}
                    <td><a href="{% return_url request 'edit_enrollment' enrollment.pk %}"> <i class="fa fa-edit"></i></a>
                    </td>
                </tr>
            {% endfor %}


            </tbody>
        </table>

    </form>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ pagenation_html|safe }}
        </ul>
    </nav>

{% endblock %}

crm/templates/form.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in form_obj %}
                    <div class="form-group {% if field.errors %}has-error{% endif %} ">
                        <label for="{{ field.id_for_label }}"
                               class="col-sm-2 col-sm-offset-1 control-label">{{ field.label }}</label>
                        <div class="col-sm-4">
                            {{ field }}
                            <span class="help-block">{{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}
                <p class="text-danger"> {{ form_obj.non_field_errors.0 }}  </p>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">保存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

crm/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type='text/css'>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>Document</title>
</head>
<body>
    <div class='container'>
        <div class='row'>
            <div class='col-md-10'></div>
        </div>
    </div>
</body> 
</html>

crm/templates/pagenation.html
{% extends "layout.html" %}

{% block content %}
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <td>id</td>
            <td>name</td>
        </tr>
        </thead>
        <tbody>
        {% for users in user %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ users }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ pagenation_html|safe }}
        </ul>
    </nav>
{% endblock %}