crm/urls.py
from django.conf.urls import url
from crm.views import auth
from crm.views import customer,teacher

urlpatterns = [
    url(r'^login/$',auth.Login.as_view(),name='login'),
    url(r'^register/$',auth.Reg.as_view(),name='register'),
    url(r'^index/$', auth.Index.as_view(), name='index'),
    # url(r'^show_customer/',customer.Customer.as_view(),name='show_customer'),
    url(r'^add_customer/$',customer.CustomerChange.as_view(),name='add_customer'),
    url(r'^edit_customer/(\d+)$',customer.CustomerChange.as_view(),name='edit_customer'),

    url(r'^public_customer/$',customer.CustomerList.as_view(),name='public_customer'),
    url(r'^private_customer/$',customer.CustomerList.as_view(),name='private_customer'),

    # 展示所有的跟进记录
    url(r'^consult_record/$',customer.ConsultList.as_view(),name='consult_record'),
    # 展示某个客户的跟进记录
    url(r'^consult_record/(\d+)$',customer.ConsultList.as_view(),name='someone_consult'),
    url(r'^add_consult/$',customer.AddConsult.as_view(),name='add_consult'),
    url(r'^edit_consult/(\d+)$',customer.EditConsult.as_view(),name='edit_consult'),
        
    url(r'^enrollment/$',customer.Enrollment.as_view(),name='enrollment'),
    url(r'^add_enrollment/(?P<customer_id>\d+)$',customer.EnrollmentChange.as_view(),name='add_enrollment'),
    url(r'^edit_enrollment/(?P<edit_id>\d+)$',customer.EnrollmentChange.as_view(),name='edit_enrollment'),
        
    url(r'^class_list/$',teacher.ClassList.as_view(),name='class_list'),
    url(r'^add_class_list/$',teacher.ClassListChange.as_view(),name='add_class_list'),
    url(r'^edit_class_list/(?P<edit_id>\d+)$',teacher.ClassListChange.as_view(),name='edit_class_list'),

    url(r'^course_record/(?P<class_id>\d+)$',teacher.CourseRecord.as_view(),name='course_record'),
    url(r'^add_course_record/(?P<class_id>\d+)$',teacher.CourseRecordChange.as_view(),name='add_course_record'),
    url(r'^edit_course_record/(?P<edit_id>\d+)$',teacher.CourseRecordChange.as_view(),name='edit_course_record'),

    url(r'^study_record_list/(?P<course_record_id>\d+)$',teacher.StudyRecordList.as_view(),name='study_record_list'),
]

practic_crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from crm import pagenation

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crm/',include('crm.urls')),
    url(r'^rbac/',include('rbac.urls',namespace='rbac')),
    # url(r'^pagenation/',pagenation.pagenation),
]

rbac/urls.py
from django.conf.urls import url
from rbac.views import role,menu


urlpatterns = [
    
    url(r'^role/list/$', role.role_list, name='show_role'),
    url(r'^role/add/$', role.role_add, name='add_role'),
    url(r'^role/edit/(\d+)$', role.role_edit,name='edit_role'),
    url(r'^role/del/(\d+)$', role.role_del,name='del_role'),

    url(r'^power/list/$', menu.power_list,name='show_power'),
    url(r'^menu/add/$', menu.menu_change,name='add_menu'),
    url(r'^menu/edit/(\d+)$', menu.menu_change,name='edit_menu'),
    url(r'^menu/del/(\d+)$', menu.menu_del,name='del_menu'),
    url(r'^power/add/$',menu.power_change,name='add_power'),
    url(r'^power/edit/(\d+)$',menu.power_change,name='edit_power'),
    url(r'^power/del/(\d+)$', menu.power_del, name='del_power'),

    url(r'^multi/power/$', menu.multi_power, name='multi_power'),
    url(r'^distribute/power/$', menu.distribute_power, name='distribute_power'),
]

rbac/models.py
from django.db import models


class Menu(models.Model):
    title = models.CharField('一级菜单', max_length=32)
    weight = models.IntegerField('权重',default=0)
    icon = models.CharField('图标', max_length=32)

    def __str__(self):
        return self.title


class Permission(models.Model):
    url = models.CharField('URL地址', max_length=128)
    title = models.CharField('标题', max_length=108)
    is_menu = models.ForeignKey('Menu', blank=True, null=True)
    parent = models.ForeignKey('self', blank=True, null=True)
    url_name = models.CharField('url别名', max_length=32, unique=True)

    class Meta:
        verbose_name = '权限'
        verbose_name_plural = '所有权限'

    def __str__(self):
        return self.title


class Role(models.Model):
    name = models.CharField('角色名称', max_length=32)
    permission = models.ManyToManyField('Permission', verbose_name='角色所拥有的权限', blank=True)

    class Meta:
        verbose_name_plural = '所有角色'

    def __str__(self):
        return self.name


class User(models.Model):
    # name = models.CharField('用户名', max_length=32)
    # pwd = models.CharField('密码', max_length=32)
    roles = models.ManyToManyField(Role, verbose_name='用户的角色', blank=True)

    class Meta():
        verbose_name_plural = '所有用户'
        abstract=True

rbac/server/routes.py
from django.conf import settings
from django.utils.module_loading import import_string
from django.urls import RegexURLResolver, RegexURLPattern
from collections import OrderedDict


def recursion_urls(pre_namespace, pre_url, urlpatterns, url_ordered_dict):
    """
    recursion_urls(None, "/", urlpatterns, url_ordered_dict)
    None, "/",        [
                url(r'^', include('web.urls')),
                url(r'^rbac/', include('rbac.urls', namespace='rbac')),
                ]

    None   "/^"

    """

    for item in urlpatterns:
        if isinstance(item, RegexURLResolver):
            if pre_namespace:
                if item.namespace:
                    namespace = "%s:%s" % (pre_namespace, item.namespace,)
                else:
                    namespace = pre_namespace
            else:
                if item.namespace:
                    namespace = item.namespace
                else:
                    namespace = None
            recursion_urls(namespace, pre_url + item.regex.pattern, item.url_patterns, url_ordered_dict)
        else:

            if pre_namespace:
                name = "%s:%s" % (pre_namespace, item.name,)
            else:
                name = item.name   # login
            if not item.name:
                raise Exception('URL路由中必须设置name属性')

            url = pre_url + item._regex  #   /login/

            url_ordered_dict[name] = {'url_name': name, 'url': url.replace('^', '').replace('$', '')}


def get_all_url_dict(ignore_namespace_list=None):
    """
    获取路由中
    :return:
    """
    ignore_list = ignore_namespace_list or []  # ignore_list  = ['admin']

    url_ordered_dict = OrderedDict()

    md = import_string(settings.ROOT_URLCONF)
    urlpatterns = []
    for item in md.urlpatterns:
        """
        [
            url(r'^', include('web.urls')),
            url(r'^rbac/', include('rbac.urls', namespace='rbac')),
        ]
        视图       RegexURLPattern 
        include    RegexURLResolver
        """
        if isinstance(item, RegexURLResolver) and item.namespace in ignore_list:
            continue
        urlpatterns.append(item)
    recursion_urls(None, "/", urlpatterns, url_ordered_dict)
    return url_ordered_dict

rbac/views/menu.py
from django.shortcuts import render,redirect,HttpResponse
from rbac import models
from crm.models import UserProfile
from rbac.form import MenuForm,PowerForm,MultiPermissionForm
from django.db.models import Q
from django.forms import modelformset_factory,formset_factory

def power_list(request):
    menu_list = models.Menu.objects.all()
    mid=request.GET.get('mid',0)
    if mid:
        power_list = models.Permission.objects.filter(Q(is_menu_id=mid)|Q(parent__is_menu_id=mid)).values('id', 'url',
            'title',
            'url_name',
            'is_menu_id',
            'parent_id',
            'is_menu__title')
    else:
        power_list = models.Permission.objects.all().values('id', 'url',
            'title',
            'url_name',
            'is_menu_id',
            'parent_id',
            'is_menu__title')
    power_dict={}
    for i in power_list:
        if i['is_menu_id']:
            i['children']=[]
            power_dict[i['id']]=i
    for j in power_list:
        if j['parent_id']:
            power_dict[j['parent_id']]['children'].append(j)
    return render(request, 'power_list.html', {'mid':mid,'menu_list': menu_list,'power_list':power_dict.values()})

# def menu_add(request):
#     """
#     新增
#     :return:
#     """
#     if request.method == 'GET':
#         form = MenuForm()
#         return render(request, 'add_role.html', {'form': form})
#     form = MenuForm(data=request.POST)
#     if form.is_valid():
#         form.save()
#         return redirect('rbac:show_power')
#     return render(request, 'add_role.html', {'form': form})
#
# def menu_edit(request, mid):
#     """
#     编辑
#     :return:
#     """
#     obj = models.Menu.objects.get(id=mid)
#     if request.method == 'GET':
#         form = MenuForm(instance=obj)
#         return render(request, 'add_role.html', {'form': form})
#     form = MenuForm(data=request.POST, instance=obj)
#     if form.is_valid():
#         form.save()
#         return redirect('rbac:show_power')
#     return render(request, 'add_role.html', {'form': form})

def menu_change(request,mid=None):
    obj = models.Menu.objects.filter(id=mid).first()
    if request.method == 'GET':
        form = MenuForm(instance=obj)
        return render(request, 'add_role.html', {'form': form})
    form = MenuForm(data=request.POST, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('rbac:show_power')
    return render(request, 'add_role.html', {'form': form})

def menu_del(request, mid):
    """
    删除角色
    :param request:
    :param cid:
    :return:
    """
    models.Menu.objects.filter(id=mid).delete()
    return redirect('rbac:show_power')

def power_del(request, pid):
    models.Permission.objects.filter(id=pid).delete()
    return redirect('rbac:show_power')


def power_change(request,pid=None):
    obj = models.Permission.objects.filter(pk=pid).first()
    if request.method == 'GET':
        form = PowerForm(instance=obj)
        return render(request, 'add_role.html', {'form': form})
    form = PowerForm(data=request.POST, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('rbac:show_power')
    return render(request, 'add_role.html', {'form': form})

from rbac.server.routes import get_all_url_dict
def multi_power(request):
    """
    批量操作权限
    :param request:
    :return:
    """
    post_type = request.GET.get('type')

    # 删除和编辑使用modelformset
    FormSet = modelformset_factory(models.Permission, MultiPermissionForm, extra=0)
    # 添加使用的formset
    AddFormSet = formset_factory(MultiPermissionForm, extra=0)

    # 获取数据中所有的权限
    permissions = models.Permission.objects.all()
    # 获取到路由系统所有的url（权限）
    router_dict = get_all_url_dict(ignore_namespace_list=['admin'])
    # 数据库中权限别名的集合
    permissions_name_set = set([i.url_name for i in permissions])
    # 路由系统中权限别名的集合
    router_name_set = set(router_dict.keys())
    # 新增权限的别名的集合
    add_name_set = router_name_set - permissions_name_set
    add_formset = AddFormSet(initial=[row for name, row in router_dict.items() if name in add_name_set])
    # print(router_dict)
    if request.method == 'POST' and post_type == 'add':
        add_formset = AddFormSet(request.POST)
        if add_formset.is_valid():
            print('pass')
            permission_obj_list = [models.Permission(**i) for i in add_formset.cleaned_data]
            query_list = models.Permission.objects.bulk_create(permission_obj_list)
            add_formset = AddFormSet()
            for i in query_list:
                permissions_name_set.add(i.url_name)
        print('no pass')
    # 删除权限的别名的集合
    del_name_set = permissions_name_set - router_name_set
    del_formset = FormSet(queryset=models.Permission.objects.filter(url_name__in=del_name_set))

    # 更新权限的别名的集合
    update_name_set = permissions_name_set & router_name_set
    update_formset = FormSet(queryset=models.Permission.objects.filter(url_name__in=update_name_set))

    if request.method == 'POST' and post_type == 'update':
        update_formset = FormSet(request.POST)
        if update_formset.is_valid():
            update_formset.save()
            update_formset = FormSet(queryset=models.Permission.objects.filter(url_name__in=update_name_set))

    return render(
        request,
        'multi_powers.html',
        {
            'del_formset': del_formset,
            'update_formset': update_formset,
            'add_formset': add_formset,
        }
    )



def distribute_power(request):
    uid = request.GET.get('uid')  # 用户的id
    rid = request.GET.get('rid')  # 角色的id

    if request.method == 'POST' and request.POST.get('postType') == 'role':
        user = UserProfile.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        user.roles.set(request.POST.getlist('roles'))

    if request.method == 'POST' and request.POST.get('postType') == 'permission' and rid:
        role = models.Role.objects.filter(id=rid).first()
        if not role:
            return HttpResponse('角色不存在')
        role.permission.set(request.POST.getlist('permissions'))

    # 所有用户
    user_list = UserProfile.objects.all()
    # 用户的角色的id
    user_has_roles = UserProfile.objects.filter(id=uid).values('id', 'roles')
    # 用户所拥有角色id的字典
    user_has_roles_dict = {item['roles']: None for item in user_has_roles}

    # 所有的角色
    role_list = models.Role.objects.all()

    if rid:
        role_has_permissions = models.Role.objects.filter(id=rid, permission__id__isnull=False).values('id',
                                                                                                        'permission')
    elif uid and not rid:
        user = UserProfile.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        role_has_permissions = user.roles.filter(permission__id__isnull=False).values('id', 'permission')
    else:
        role_has_permissions = []
    # 某一个角色所拥有的权限   某一个用户所拥有的所有的权限
    role_has_permissions_dict = {item['permission']: None for item in role_has_permissions}
    # 所有菜单
    all_menu_list = []
    """
     all_menu_list =  [ 
         { id  title  children :[
                 { 'id', 'title', 'menu_id'  'children' : [
                     {'id', 'title', 'parent_id'}
                 ]   } 
         ] }
         {'id': None, 'title': '其他', 'children': [
             {'id', 'title', 'parent_id'}
         ]}
     ]

    """
    queryset = models.Menu.objects.values('id', 'title')  # 一级菜单的id 和 标题  [ { id  title } ]
    # 菜单的字典
    menu_dict = {}
    """
    menu_dict = {
        一级菜单的id： { id  title  children :[
            { 'id', 'title', 'menu_id'  'children' : [
                    {'id', 'title', 'parent_id'}
                ]   } 
        ] },
        None: {'id': None, 'title': '其他', 'children': [
            {'id', 'title', 'parent_id'}
        ]}
    }
    """

    for item in queryset:  # { id  title }
        item['children'] = []  # { id  title  children :[]  }
        menu_dict[item['id']] = item
        all_menu_list.append(item)

    other = {'id': None, 'title': '其他', 'children': []}
    all_menu_list.append(other)
    menu_dict[None] = other
    # 二级菜单  父权限
    root_permission = models.Permission.objects.filter(is_menu__isnull=False).values('id', 'title', 'is_menu_id')

    root_permission_dict = {}
    """
    root_permission_dict = {
            父权限的id： { 'id', 'title', 'menu_id'  'children' : [
                {'id', 'title', 'parent_id'}
            ]   } 
    }
    """

    for per in root_permission:  # { 'id', 'title', 'menu_id' }
        per['children'] = []  # { 'id', 'title', 'menu_id'  'children' : []   }
        nid = per['id']
        menu_id = per['is_menu_id']
        root_permission_dict[nid] = per
        menu_dict[menu_id]['children'].append(per)

    node_permission = models.Permission.objects.filter(is_menu__isnull=True).values('id', 'title', 'parent_id')

    for per in node_permission:  # {'id', 'title', 'parent_id'}
        pid = per['parent_id']
        if not pid:
            menu_dict[None]['children'].append(per)
            continue
        root_permission_dict[pid]['children'].append(per)
    return render(
        request,
        'distribute_power.html',
        {
            'user_list': user_list,  # 所有的用户
            'role_list': role_list,  # 所有的角色
            'user_has_roles_dict': user_has_roles_dict,  # 当前用户所拥有的角色
            'role_has_permissions_dict': role_has_permissions_dict,  # 某一个角色所拥有的权限   某一个用户所拥有的所有的权限
            'all_menu_list': all_menu_list,  # 所有的菜单信息 父权限 子权限  普通的权限
            'uid': uid,
            'rid': rid
        }
    )

rbac/views/role.py
from django.shortcuts import render,redirect
from rbac import models
from rbac.form import RoleForm

def role_list(request):
    """
    客户列表
    :return:
    """
    data_list = models.Role.objects.all()

    return render(request, 'role_list.html', {'data_list': data_list})

def role_add(request):
    """
    新增
    :return:
    """
    if request.method == 'GET':
        form = RoleForm()
        return render(request, 'add_role.html', {'form': form})
    form = RoleForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('rbac:show_role')
    return render(request, 'add_role.html', {'form': form})

def role_edit(request, rid):
    """
    编辑
    :return:
    """
    obj = models.Role.objects.get(id=rid)
    if request.method == 'GET':
        form = RoleForm(instance=obj)
        return render(request, 'add_role.html', {'form': form})
    form = RoleForm(data=request.POST, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('rbac:show_role')
    return render(request, 'add_role.html', {'form': form})

def role_del(request, rid):
    """
    删除角色
    :param request:
    :param cid:
    :return:
    """
    models.Role.objects.filter(id=rid).delete()
    return redirect('rbac:show_role')

rbac/templates/add_role.html
{% extends 'layout.html' %}
{% block my_css %}
    <style>

        .icon-area ul {
            list-style-type: none;
            padding: 0;
        }

        .icon-area ul li {
            float: left;
            padding: 10px;
            padding-left: 0;
            width: 80px;
        }

        .icon-area ul li i {
            font-size: 18px;
            margin-left: 5px;
            color: #6d6565;
        }

    </style>

{% endblock %}
{% block content %}
    <div class="luffy-container">
        <form class="form-horizontal clearfix" method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group {% if field.errors %} has-error{% endif %} col-md-9 clearfix">
                    <label for="{{ field.id_for_label }}" class="col-sm-3 control-label">{{ field.label }}</label>
                    <div class="col-sm-9 icon-area">
                        {{ field }} <span id="helpBlock2" class="help-block">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <p class="text-danger text-center"> {{ form_obj.non_field_errors.0 }} </p>
            <div class="form-group col-sm-12">
                <div class="col-sm-6">
                    <div class="col-sm-offset-3">
                        <button type="submit" class="btn btn-primary">提 交</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

rbac/templates/breadcrumb.html
<ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">
    {% for breadcrumb in breadcrumb_list %}
        {% if forloop.last %}
            <li class="active">{{ breadcrumb.title }}</li>
        {% else %}
            <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.title }}</a></li>
        {% endif %}
    {% endfor %}
</ol>

rbac/templates/index.html
{% extends 'layout.html' %}

{% block content %}
<h1>欢迎登录</h1>
    <h3>{{ cur_user }}</h3>
{% endblock %}

rbac/templates/menu.html
{#{% for menu in menu_list %}#}
{#    <a href="{{ menu.url }}" class="{{ menu.class }}">#}
{#    <span class="icon-wrap"><i class="fa {{ menu.icon }}"></i></span> {{ menu.titlt }}</a>#}
{#{% endfor %}#}



<div class="my_click multi-menu">
{% for menu in menu_list %}
    <div class="item">
        <div class="title"> <i class="fa {{ menu.icon }}"></i> {{ menu.title }}</div>
        <div class="body {{ menu.class }}">
        {% for foo in menu.children %}
            <a class="{{ foo.class }}" href="{{ foo.url }}">{{ foo.title }}</a>
        {% endfor %}
        </div>
    </div>
{% endfor %}
</div>

rbac/templates/power_list.html
{% extends 'layout.html' %}

{% block my_css %}
    <style>

    .root {
    background-color: #fdf8c0;
    }

    .aaaaaa {
    background-color: #fdeac0;
    border-left: 3px solid #fdc00f;
    }
    </style>

{% endblock %}

{% block content %}
    {% load my_tags %}
    <div class="luffy-container">
        <div class="row">
            <div class="col-md-3">
                <table class="table table-bordered table-hover">
                    <caption style="background-color: #d6d3d3" class="">
                        &emsp;<i class="fa fa-id-card-o" aria-hidden="true"></i>
                        <span style="color: black">菜单管理</span>
                        <a class="pull-right btn btn-success btn-xs" href="{% url 'rbac:add_menu' %}"
                           style="margin-right: 8px;">
                            <i class="fa fa-plus-square" aria-hidden="true"></i> 新建
                        </a>&emsp;
                    </caption>
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>图标</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for row in menu_list %}
                        <tr class="{% if mid == row.id|safe %}aaaaaa{% endif %}">
                            <td><a href="?mid={{ row.id }}">{{ row.title }}</a></td>
                            <td><i class="fa {{ row.icon }}" aria-hidden="true"></i></td>
                            <td>
                                <a style="color: #333333;" href="{% url 'rbac:edit_menu' row.id %}">
                                    <i class="fa fa-edit" aria-hidden="true"></i></a>
                                |
                                <a style="color: #d9534f;" href="{% url 'rbac:del_menu' row.id %}"><i
                                        class="fa fa-trash-o"></i></a>
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-md-9">
                <table class="table table-bordered table-hover">
                    <caption style="background-color: #d6d3d3" class="">
                        &emsp;<i class="fa fa-puzzle-piece" aria-hidden="true"></i>
                        <span style="color: black">权限管理</span>
                        <a class="pull-right btn btn-success btn-xs" href="{% url 'rbac:add_power' %}" style="margin-right: 8px;">
                            <i class="fa fa-plus-square" aria-hidden="true"></i> 新建
                        </a>
                        <a class="pull-right btn btn-success btn-xs" href="{% url 'rbac:multi_power' %}" style="margin-right: 8px;">
                            <i class="fa fa-reply-all" aria-hidden="true"></i> 批量操作
                        </a>
                    </caption>
                    <thead>
                    <tr>
                        <th>名称</th>
                        <th>URL</th>
                        <th>URL别名</th>
                        <th>菜单</th>
                        <th>所属菜单</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for row2 in power_list %}
                        <tr class="root">
                            <td class="my_name" id="{{ row2.id }}">
                                <i class="fa fa-caret-down"></i>{{ row2.title }}</td>
                            <td>{{ row2.url }}</td>
                            <td>{{ row2.url_name }}</td>
                            <td> <p style="color: green">YES</p></td>
                            <td>{{ row2.is_menu__title }}</td>
                            <td>
                                <a style="color: #333333;" href="{% url 'rbac:edit_power' row2.id %}">
                                    <i class="fa fa-edit" aria-hidden="true"></i></a>
                                |
                                <a style="color: #d9534f;" href="{% url 'rbac:del_power' row2.id %}"><i class="fa fa-trash-o"></i></a>
                            </td>
                        </tr>
                        {% for row3 in row2.children %}
                        <tr pid="{{ row3.parent_id }}">
                            <td>{{ row3.title }}</td>
                            <td>{{ row3.url }}</td>
                            <td>{{ row3.url_name }}</td>
                            <td></td>
                            <td></td>
                            <td>
                                <a style="color: #333333;" href="{% url 'rbac:edit_power' row3.id %}">
                                    <i class="fa fa-edit" aria-hidden="true"></i></a>
                                |
                                <a style="color: #d9534f;" href="{% url 'rbac:del_power' row3.id %}"><i class="fa fa-trash-o"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
<script>
    $('.my_name').click(function () {
        pid = $(this).attr('id');
        caret = $(this).find('i');
        if (caret.hasClass('fa-caret-down')) {
            caret.removeClass('fa-caret-down').addClass('fa-caret-right');
        } else {
            caret.removeClass('fa-caret-right').addClass('fa-caret-down');
        }
        tr = $(this).parent().nextAll("[pid=" + pid + "]");
        tr.toggleClass('hide');
    })
</script>
{% endblock %}

rbac/templates/role_list.html
{% extends 'layout.html' %}

{% block content %}
{% load my_tags %}
    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">
{#            {% if request|has_permission:'add' %}#}
            <a class="btn btn-success" href="{% url 'rbac:add_role' %}">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加角色
            </a>
{#            {% endif %}#}
        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>角色名称</th>
                <th>选项</th>
            </tr>
            </thead>
            <tbody>
            {% for row in data_list %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.name }}</td>
                    <td>
                        <a style="color: #333333;" href="{% url 'rbac:edit_role' row.id %}">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        |
                        <a style="color: #d9534f;" href="{% url 'rbac:del_role' row.id %}"><i class="fa fa-trash-o"></i></a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}